vim.api.nvim_create_autocmd("FileType", {
  pattern = {
    "ada", "astro", "awk", "axaml", "bash", "bat", "blade", "blueprint", "c", 
    "c_sharp", "clojure", "cmake", "cobol", "cpp", "crystal", "cs_project", "css", 
    "cue", "dart", "delphi", "django", "dockerfile", "d", "elixir", "erlang", 
    "fennel", "fortran", "forth", "fsharp", "fsharp_project", "gdscript", "gleam", 
    "glimmer", "go", "graphql", "groovy", "handlebars", "haskell", "haxe", "hcl", 
    "html", "hyprlang", "idris", "ini", "ipynb", "java", "javascript", "javascriptreact", 
    "jinja", "julia", "js", "jsx", "json", "kdl", "kotlin", "less", "lisp", 
    "logtalk", "lua", "make", "matlab", "nim", "objectivec", "ocaml", "perl", 
    "php", "pike", "plsql", "powershell", "prolog", "python", "r", "racket", 
    "rego", "rescript", "rexx", "ruby", "rust", "sass", "scala", "scheme", "scss", 
    "sh", "smalltalk", "sql", "styled", "svelte", "swift", "templ", "terraform", 
    "tcl", "tex", "toml", "twig", "tsx", "typescript", "typescriptreact", "vala", 
    "verilog", "vim", "vhdl", "vue", "xaml", "yaml", "zig"
  },
  callback = function()
    local comment_styles = {
      ada = "-- %s",
      astro = "<!-- %s -->",
      awk = "# %s",
      axaml = "<!-- %s -->",
      bash = "# %s",
      bat = "REM %s",
      blade = "{{-- %s --}}",
      blueprint = "// %s",
      c = "// %s",
      c_sharp = "// %s",
      clojure = { ";; %s", "; %s" },
      cmake = "# %s",
      cobol = "* %s",
      cpp = "// %s",
      crystal = "# %s",
      cs_project = "<!-- %s -->",
      css = "/* %s */",
      cue = "// %s",
      dart = "// %s",
      delphi = "// %s",
      django = "{# %s #}",
      dockerfile = "# %s",
      d = "// %s",
      elixir = "# %s",
      erlang = "% %s",
      fennel = "-- %s",
      forth = "\\ %s",
      fortran = "! %s",
      fsharp = "// %s",
      fsharp_project = "<!-- %s -->",
      gdscript = "# %s",
      gleam = "// %s",
      glimmer = "{{! %s }}",
      go = "// %s",
      graphql = "# %s",
      groovy = "// %s",
      handlebars = "{{! %s }}",
      haskell = "-- %s",
      haxe = "// %s",
      hcl = "# %s",
      html = "<!-- %s -->",
      hyprlang = "# %s",
      idris = "-- %s",
      ini = "; %s",
      ipynb = "# %s",
      java = "// %s",
      javascript = "// %s",
      javascriptreact = "// %s",
      jinja = "{# %s #}",
      julia = "# %s",
      js = "// %s",
      jsx = { "// %s", "/* %s */", "{/* %s */}" },
      json = "// %s",
      kdl = "// %s",
      kotlin = "// %s",
      less = "/* %s */",
      lisp = ";; %s",
      logtalk = "% %s",
      lua = "-- %s",
      make = "# %s",
      matlab = "% %s",
      nim = "# %s",
      objectivec = "// %s",
      ocaml = "(* %s *)",
      perl = "# %s",
      php = "// %s",
      pike = "// %s",
      plsql = "-- %s",
      powershell = "# %s",
      prolog = "% %s",
      python = "# %s",
      r = "# %s",
      racket = ";; %s",
      rego = "# %s",
      rescript = "// %s",
      rexx = "-- %s",
      ruby = "# %s",
      rust = { "// %s", "/* %s */" },
      sass = "/* %s */",
      scala = "// %s",
      scheme = ";; %s",
      scss = "/* %s */",
      sh = "# %s",
      smalltalk = '" %s',
      sql = "-- %s",
      styled = "/* %s */",
      svelte = "<!-- %s -->",
      swift = "// %s",
      templ = { "// %s", component_block = "<!-- %s -->" },
      terraform = "# %s",
      tcl = "# %s",
      tex = "%% %s",
      toml = "# %s",
      twig = "{# %s #}",
      tsx = { "// %s", "/* %s */", "{/* %s */}" },
      typescript = { "// %s", "/* %s */" },
      typescriptreact = "// %s",
      vala = "// %s",
      verilog = "// %s",
      vim = '" %s',
      vhdl = "-- %s",
      vue = "<!-- %s -->",
      xaml = "<!-- %s -->",
      yaml = "# %s",
      zig = "// %s"
    }

    local filetype = vim.bo.filetype
    if comment_styles[filetype] then
      vim.bo.commentstring = comment_styles[filetype]
    end
  end,
})

